### ISSUE TITLE
Cannot navigate to source location

### ISSUE THREAD

**Issue by LittleHuba** [advanced-security/SARIF-viewer#68]
Gateway Version: 2023.3.4
CLion Version: 2023.3.4
Plugin Version: 1.2.0

When clicking on a finding in the SARIF viewer, I would expect it to navigate to the location in the source.

Instead, nothing happens.

Maybe this is connected to using CLion through Jetbrains Gateway, but this might also be unrelated.

**Comment by adrienpessu** [comment]
Hello @LittleHuba,

I just took the time to test the SARIF viewer plugin with JetBrain Gateway. I am able to navigate to the location in the source.

How did you get the SARIF file? Did you use the GitHub integration or just import a local SARIF file ?

**Comment by LittleHuba** [comment]
Thanks for the reply!

I used a local SARIF file that I imported.

**Comment by adrienpessu** [comment]
ok, the SARIF file may not have the same path or at least doesn't start the relative path at the root of your CLion workspace. 

Maybe I need to add a quick message to explain that when the location can't be resolved.

**Comment by LittleHuba** [comment]
Hi,
I looked at the SARIF file again and the paths start at the root of the CLion workspace and the file is present under the exact path.

Can I provide some kind of debug logs? I did not find anything in the logs of the IDE.

**Comment by adrienpessu** [comment]
Hello, 

I have released a new version that fix an issue when navigating into file in the steps. I also added a message when we can't resolve the location. 

Let me know if it helped
